# Automatic Ripping Machine Docker Compose File
services:
  # Image for Automatic Ripping Machine User Interface (UI) AKA Webpage
  arm-ui:
    build:
      context: ./
      dockerfile: Dockerfile-UI
    image: automaticrippingmachine/arm-ui:3.0.dev
    container_name: arm-ui
    ports:
      - "8080:8080"
    environment:
      # ARM environment variables and configuration
      - ARM_UID=1000            # Set this to the id of the user, as per the below volumes
      - ARM_GID=1000            # Set this to the id of the group, as per below volumes
      - FLASK_ENV=development   # leave this commented out unless running in development or there are UI bugs
      - MYSQL_IP=arm-db         # leave unless the ARM database is on another machine
      - MYSQL_USER=arm          # this should match the MySQL database user
      - MYSQL_PASSWORD=example  # this should match the MySQL database password
      - TZ=Etc/UTC              # set to your local timezone
    volumes:
      # Volumes for ARM 'local directory':'ARM container directory'
      - /arm/db:/arm/db
      - /arm/logs:/arm/logs
      - /arm/config:/arm/config
    logging:
      # Docker log rotate settings, max file size and number of files
      options:
        max-size: "10m"
        max-file: "1"
    depends_on:
#      - arm-db
      - arm-db-test  # use for testing of arm
    networks:
      - arm-network
    restart: unless-stopped

  # Image for Automatic Ripping Machine Ripper
#  arm-ripper:
#    build:
#      context: ./
#      dockerfile: Dockerfile-Ripper
#    image: automaticrippingmachine/arm-ripper:3.0.0_dev
#    container_name: arm-ripper:3.0.0_dev
#    ports:
#      - "8080:8080"
#    environment:
#      # ARM environment variables and configuration
#      - ARM_UID=1001            # Set this to the id of the user, as per the below volumes
#      - ARM_GID=1001            # Set this to the id of the group, as per the below volumes
#      - MYSQL_IP=arm-db         # leave unless the ARM database is on another machine
#      - MYSQL_USER=arm          # this should match the MySQL database user
#      - MYSQL_PASSWORD=example  # this should match the MySQL database password
#      - TZ=Etc/UTC              # set to your local timezone
#    volumes:
#      # Volumes for ARM 'local directory':'ARM container directory'
#      - /home/arm:/home/arm
#      - /home/arm/music:/home/arm/music
#      - /home/arm/logs:/home/arm/logs
#      - /home/arm/media:/home/arm/media
#      - /home/arm/config:/etc/arm/config
#      #devices:
#      - "/dev/sr0:/dev/sr0"
#      - "/dev/sr1:/dev/sr1"
#      - "/dev/sr2:/dev/sr2"
#      - "/dev/sr3:/dev/sr3"
#      - "/dev/sr4:/dev/sr4"
#      - "/dev/sr5:/dev/sr5"
#    logging:
#      # Docker log rotate settings, max file size and number of files
#      options:
#        max-size: "10m"
#        max-file: "1"
#    depends_on:
#      - arm-db
#    networks:
#      - arm-network
#    restart: unless-stopped

  # Image for the Automatic Ripping Machine Database, using MySql
  arm-db:
    image: mysql:8.3.0
    container_name: arm-db
    user: 1000:1000                     # Set this to the user and group id of the below volume
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: arm
      MYSQL_USER: arm
      MYSQL_PASSWORD: example
    volumes:
      # Volumes for ARM db 'local directory':'MYSQL directory'
      - /arm/db/mysql:/var/lib/mysql
    networks:
      - arm-network
    restart: unless-stopped

# ARM MYSQL Test Database, details on setup in the ARM Wiki
  arm-db-test:
    image: mysql:8.3.0
    container_name: arm-db-test
    user: 1000:1000                     # Set this to the owner of the data volumes
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: arm_testing
      MYSQL_USER: arm
      MYSQL_PASSWORD: example
    volumes:
      # Testing uses a temporary volume, restarting the container will remove all test data
      - type: tmpfs
        target: /var/lib/mysql
    networks:
      - arm-network
    restart: no

networks:
  arm-network:
